title:            Wangxin's Blog
description:      一些笔记和文章。。。
disqus_shortname: 
reading_time:     false
words_per_minute: 200
logo:             images/logo.png
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: '首页'
    url: '/'
  - title: '机器学习'
    url: '/machine-learning'
    submenu:
      - title: '计算机视觉'
        url: '/computer-vision'
      - title: '机器学习基础'
        url: '/ml-basic'
  - title: '技术基础'
    url: '/tech'
    submenu:
      - title: '程序语言'
        url: '/program'
      - title: '其他'
        url: '/others'
  - title: '艺术'
    url: '/art'
    submenu:
      - title: '艺术史'
        url: '/art-history'
      - title: '艺术理论'
        url: '/art-theory'
      - title: '美学'
        url: '/aesthetics'
  - title: '标签'
    url: '/tags'

# Owner/author information
owner:
  name:           Wangxin
  avatar:         images/logo.png
  bio:            "呵呵"
  email:          flybird1987@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         einsteinliu
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-80848870-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 8

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
